---
inet_routers:
    hosts: 
      inetRouter:
        ansible_host: 127.0.0.1
        ansible_port: 2201
        ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key

office_routers:
    hosts:
      centralRouter:
        ansible_host: 127.0.0.1
        ansible_port: 2202
        ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key
      office1Router:
        ansible_host: 127.0.0.1
        ansible_port: 2203
        ansible_private_key_file: .vagrant/machines/office1Router/virtualbox/private_key
      office2Router:
        ansible_host: 127.0.0.1
        ansible_port: 2204
        ansible_private_key_file: .vagrant/machines/office2Router/virtualbox/private_key
          
servers:
    hosts:
      centralServer:
        ansible_host: 127.0.0.1
        ansible_port: 2205
        ansible_private_key_file: .vagrant/machines/centralServer/virtualbox/private_key
      office1Server:  
        ansible_host: 127.0.0.1
        ansible_port: 2206
        ansible_private_key_file: .vagrant/machines/office1Server/virtualbox/private_key
      office2Server:  
        ansible_host: 127.0.0.1
        ansible_port: 2207
        ansible_private_key_file: .vagrant/machines/office2Server/virtualbox/private_key  
        
      
          
